### ISSUE TITLE
Automate Modulesync

### ISSUE THREAD

**Issue by jacksgt** [vision-it/modulesync_configs#1]
What do you think about automating modulesync in CI so all dependencies can be updated by clicking a single button?

We could add SSH keys and run it on our internal CI server, then the CI can automatically submit pull requests (https://github.com/vision-bot).

**Comment by martialblog** [comment]
Technically you can do that in a single command with msync update and the managed_modules file.

**Comment by martialblog** [comment]
Ich habe jetzt auf die neue modulesync Version umgestellt. Damit ist das Upgraden aller Module ein Befehl: 

```
# Update ALL
 bundle exec msync update
# Update ONE
 bundle exec msync update -f vision-ha
```
